module.exports = {
  ADMIN_LOAD_BOOKS: 'ADMIN_LOAD_BOOKS',
  ADMIN_LOAD_BOOKS_SUCCESS: 'ADMIN_LOAD_BOOKS_SUCCESS',
  ADMIN_LOAD_BOOKS_ERROR: 'ADMIN_LOAD_BOOKS_ERROR',

  ADMIN_LOAD_MEMBERS: 'ADMIN_LOAD_MEMBERS',
  ADMIN_LOAD_MEMBERS_SUCCESS: 'ADMIN_LOAD_MEMBERS_SUCCESS',
  ADMIN_LOAD_MEMBERS_ERROR: 'ADMIN_LOAD_MEMBERS_ERROR',

  ADMIN_LOAD_REQUESTS: 'ADMIN_LOAD_REQUESTS',
  ADMIN_LOAD_REQUESTS_SUCCESS: 'ADMIN_LOAD_REQUESTS_SUCCESS',
  ADMIN_LOAD_REQUESTS_ERROR: 'ADMIN_LOAD_REQUESTS_ERROR',

  ADMIN_UPDATE_BOOK: 'ADMIN_UPDATE_BOOK',
  ADMIN_UPDATE_BOOK_SUCCESS: 'ADMIN_UPDATE_BOOK_SUCCESS',
  ADMIN_UPDATE_BOOK_ERROR: 'ADMIN_UPDATE_BOOK_ERROR',

  ADMIN_CREATE_BOOK: 'ADMIN_CREATE_BOOK',
  ADMIN_CREATE_BOOK_SUCCESS: 'ADMIN_CREATE_BOOK_SUCCESS',
  ADMIN_CREATE_BOOK_ERROR: 'ADMIN_CREATE_BOOK_ERROR',

  ADMIN_LOAD_POSTMEN: 'ADMIN_LOAD_POSTMEN',
  ADMIN_LOAD_POSTMEN_SUCCESS: 'ADMIN_LOAD_POSTMEN_SUCCESS',
  ADMIN_LOAD_POSTMEN_ERROR: 'ADMIN_LOAD_POSTMEN_ERROR',

  ADMIN_ALLOCATE_REQUEST_TO_POSTMAN_SUCCESS: 'ADMIN_ALLOCATE_REQUEST_TO_POSTMAN_SUCCESS',
  ADMIN_ALLOCATE_REQUEST_TO_POSTMAN_ERROR: 'ADMIN_ALLOCATE_REQUEST_TO_POSTMAN_ERROR',

  ADMIN_UPDATE_MEMBER_PROFILE_SUCCESS: 'ADMIN_UPDATE_MEMBER_PROFILE_SUCCESS',
  ADMIN_UPDATE_MEMBER_PROFILE_ERROR: 'ADMIN_UPDATE_MEMBER_PROFILE_ERROR',

  ADMIN_CONFIRM_MEMBER_MONTHLY_FEE_SUCCESS: 'ADMIN_CONFIRM_MEMBER_MONTHLY_FEE_SUCCESS',
  ADMIN_CONFIRM_MEMBER_MONTHLY_FEE_ERROR: 'ADMIN_CONFIRM_MEMBER_MONTHLY_FEE_ERROR',

  ADMIN_CONFIRM_MEMBER_DEPOSIT_SUCCESS: 'ADMIN_CONFIRM_MEMBER_DEPOSIT_SUCCESS',
  ADMIN_CONFIRM_MEMBER_DEPOSIT_ERROR: 'ADMIN_CONFIRM_MEMBER_DEPOSIT_ERROR',

  ADMIN_APPROVE_MEMBER_APPLICATION_SUCCESS: 'ADMIN_APPROVE_MEMBER_APPLICATION_SUCCESS',
  ADMIN_APPROVE_MEMBER_APPLICATION_ERROR: 'ADMIN_APPROVE_MEMBER_APPLICATION_ERROR',

  ADMIN_CONFIRM_MEMBER_START_TRIAL_SUCCESS: 'ADMIN_CONFIRM_MEMBER_START_TRIAL_SUCCESS',
  ADMIN_CONFIRM_MEMBER_START_TRIAL_ERROR: 'ADMIN_CONFIRM_MEMBER_START_TRIAL_ERROR'
};
