module.exports = {
  ADMIN_LOAD_BOOKS: 'ADMIN_LOAD_BOOKS',
  ADMIN_LOAD_BOOKS_SUCCESS: 'ADMIN_LOAD_BOOKS_SUCCESS',
  ADMIN_LOAD_BOOKS_ERROR: 'ADMIN_LOAD_BOOKS_ERROR',

  ADMIN_LOAD_MEMBERS: 'ADMIN_LOAD_MEMBERS',
  ADMIN_LOAD_MEMBERS_SUCCESS: 'ADMIN_LOAD_MEMBERS_SUCCESS',
  ADMIN_LOAD_MEMBERS_ERROR: 'ADMIN_LOAD_MEMBERS_ERROR',

  ADMIN_LOAD_REQUESTS: 'ADMIN_LOAD_REQUESTS',
  ADMIN_LOAD_REQUESTS_SUCCESS: 'ADMIN_LOAD_REQUESTS_SUCCESS',
  ADMIN_LOAD_REQUESTS_ERROR: 'ADMIN_LOAD_REQUESTS_ERROR',

  ADMIN_UPDATE_BOOK: 'ADMIN_UPDATE_BOOK',
  ADMIN_UPDATE_BOOK_SUCCESS: 'ADMIN_UPDATE_BOOK_SUCCESS',
  ADMIN_UPDATE_BOOK_ERROR: 'ADMIN_UPDATE_BOOK_ERROR',

  ADMIN_CREATE_BOOK: 'ADMIN_CREATE_BOOK',
  ADMIN_CREATE_BOOK_SUCCESS: 'ADMIN_CREATE_BOOK_SUCCESS',
  ADMIN_CREATE_BOOK_ERROR: 'ADMIN_CREATE_BOOK_ERROR'  
};
