module.exports = {
  COMMON_USER_RESET_PASSWORD: 'COMMON_USER_RESET_PASSWORD',
  COMMON_USER_RESET_PASSWORD_SUCCESS: 'COMMON_USER_RESET_PASSWORD_SUCCESS',
  COMMON_USER_RESET_PASSWORD_ERROR: 'COMMON_USER_RESET_PASSWORD_ERROR',

  GET_PUBLIC_USER_PROFILE: 'GET_PUBLIC_USER_PROFILE_QUERY',
  GET_PUBLIC_USER_PROFILE_SUCCESS: 'GET_PUBLIC_USER_PROFILE_SUCCESS',
  GET_PUBLIC_USER_PROFILE_ERROR: 'GET_PUBLIC_USER_PROFILE_ERROR',

  USER_LOGIN: 'USER_LOGIN',
  USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  USER_LOGIN_ERROR: 'USER_LOGIN_ERROR',

  USER_UPDATE: 'USER_UPDATE',
  USER_UPDATE_SUCCESS: 'USER_UPDATE_SUCCESS',
  USER_UPDATE_ERROR: 'USER_UPDATE_ERROR',

  GET_USER: 'GET_USER',
  GET_USER_SUCCESS: 'GET_USER_SUCCESS',
  GET_USER_ERROR: 'GET_USER_ERROR',

  LOAD_WAREHOUSES: 'LOAD_WAREHOUSES',
  LOAD_WAREHOUSES_SUCCESS: 'LOAD_WAREHOUSES_SUCCESS',
  LOAD_WAREHOUSES_ERROR: 'LOAD_WAREHOUSES_ERROR',

  LOAD_BOOKS: 'LOAD_BOOKS',
  LOAD_BOOKS_SUCCESS: 'LOAD_BOOKS_SUCCESS',
  LOAD_BOOKS_ERROR: 'LOAD_BOOKS_ERROR',

  GET_BOOK_SUCCESS: 'GET_BOOK_SUCCESS',
  GET_BOOK_ERROR: 'GET_BOOK_ERROR',

  GET_BOOK_REVIEWS_SUCCESS: 'GET_BOOK_REVIEWS_SUCCESS',
  GET_BOOK_REVIEWS_ERROR: 'GET_BOOK_REVIEWS_ERROR',

  GET_NEW_MEMBER_APPLICATION_SUCCESS: 'GET_NEW_MEMBER_APPLICATION_SUCCESS',
  GET_NEW_MEMBER_APPLICATION_ERROR: 'GET_NEW_MEMBER_APPLICATION_ERROR'  
};
