module.exports = {
  MEMBER_BORROW_REQUEST_SUCCESS: 'MEMBER_BORROW_REQUEST_SUCCESS',
  MEMBER_BORROW_REQUEST_ERROR: 'MEMBER_BORROW_REQUEST_ERROR',

  MEMBER_RETURN_REQUEST_SUCCESS: 'MEMBER_RETURN_REQUEST_SUCCESS',
  MEMBER_RETURN_REQUEST_ERROR: 'MEMBER_RETURN_REQUEST_ERROR',

  MEMBER_ADD_COMMENT_SUCCESS: 'MEMBER_ADD_COMMENT_SUCCESS',
  MEMBER_ADD_COMMENT_ERROR: 'MEMBER_ADD_COMMENT_ERROR',

  MEMBER_GET_MYBOOK_REQUESTS_SUCCESS: 'MEMBER_GET_MYBOOK_REQUESTS_SUCCESS',
  MEMBER_GET_MYBOOK_REQUESTS_ERROR: 'MEMBER_GET_MYBOOK_REQUESTS_ERROR',

  MEMBER_GET_MYBORROWED_BOOKS_SUCCESS: 'MEMBER_GET_MYBORROWED_BOOKS_SUCCESS',
  MEMBER_GET_MYBORROWED_BOOKS_ERROR: 'MEMBER_GET_MYBORROWED_BOOKS_ERROR',

  MEMBER_GET_THISWEEK_BOOKBOX_ERROR: 'MEMBER_GET_THISWEEK_BOOKBOX_ERROR',
  MEMBER_GET_THISWEEK_BOOKBOX_SUCCESS: 'MEMBER_GET_THISWEEK_BOOKBOX_SUCCESS'
};
