module.exports = {
  MEMBER_BORROW_REQUEST_SUCCESS: 'MEMBER_BORROW_REQUEST_SUCCESS',
  MEMBER_BORROW_REQUEST_ERROR: 'MEMBER_BORROW_REQUEST_ERROR',

  MEMBER_RETURN_REQUEST_SUCCESS: 'MEMBER_RETURN_REQUEST_SUCCESS',
  MEMBER_RETURN_REQUEST_ERROR: 'MEMBER_RETURN_REQUEST_ERROR',

  MEMBER_ADD_COMMENT_SUCCESS: 'MEMBER_ADD_COMMENT_SUCCESS',
  MEMBER_ADD_COMMENT_ERROR: 'MEMBER_ADD_COMMENT_ERROR'
};
