module.exports = {
  POSTMAN_CONFIRM_SUCCESS: 'POSTMAN_CONFIRM_SUCCESS',
  POSTMAN_CONFIRM_ERROR: 'POSTMAN_CONFIRM_ERROR',

  POSTMAN_GET_MYREQUESTS_SUCCESS: 'POSTMAN_GET_MYREQUESTS_SUCCESS',
  POSTMAN_GET_MYREQUESTS_ERROR: 'POSTMAN_GET_MYREQUESTS_ERROR'
};
